name: Build and Push ArcGIS Windows Container Image

on:
  push:
    branches: [main]
  # allow it to be run on-demand
  workflow_dispatch:

# Starts jobs and sets the type of runner (Windows) they will run on
jobs:
  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Github Packages
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        env:
          ARCGIS_PRO_3_CAB_URL: ${{ secrets.ARCGIS_PRO_3_CAB_URL }}
          ARCGIS_PRO_3_CAB1_URL: ${{ secrets.ARCGIS_PRO_3_CAB1_URL }}
          ARCGIS_PRO_3_MSI_URL: ${{ secrets.ARCGIS_PRO_3_MSI_URL }}
        run: |
          docker build -f arcgis/ArcGISPro.Windows.Dockerfile -t ghcr.io/jtroe/cicd/arcgispro:3.0-latest --build-arg ARCGIS_PRO_3_CAB_URL=$ARCGIS_PRO_3_CAB_URL --build-arg ARCGIS_PRO_3_CAB1_URL=$ARCGIS_PRO_3_CAB1_URL --build-arg ARCGIS_PRO_3_MSI_URL=$ARCGIS_PRO_3_MSI_URL .
      
      - name:  Push container to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ghcr.io/jtroe/cicd/arcgispro:3.0-latest