name: DockerBuildCondaBuildWindows

on:
  workflow_run:
    workflows: [DockerBuildCondaWindows]
    types: [completed]
  # allow it to be run on-demand
  workflow_dispatch:

# Starts jobs and sets the type of runner (Windows) they will run on
jobs:
  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_dispatch != null }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Github Packages
        uses: azure/docker-login@v1
        with:
          login-server: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -f python/CondaBuild.Windows.Dockerfile -t ghcr.io/jtroe/cicd-container-images/condabuild-windows:latest .
      
      - name:  Push container to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push ghcr.io/jtroe/cicd-container-images/condabuild-windows:latest