name: Build and Push CondaBuild Windows Container Image

on:
  push:
    branches: [main]
  workflow_dispatch: # allow it to be run on-demand

jobs:
  build:
    name: Build image and push to GitHub Container Registry
    runs-on: windows-latest

    steps:
      - id: gh_checkout
        name: Checkout code
        uses: actions/checkout@v3

      - id: docker_build
        name: Build image and push to GitHub Container Registry
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ghcr.io/arcgis/images/python.conda.windows
          dockerfile: ./python/CondaBuild.Windows.Dockerfile
          platform: windows/amd64
          addLatest: true
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}