# Build and Push Sphinx Read The Docs Container Image
name: DockerBuildSphinxRTD

on:
  # push:
  #  branches: [main]
  # allow it to be run on-demand
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/jtroe/cicd-container-images/sphinx-rtd
          tags: |
            type=raw,value=3.2.1
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YY.MM'}},enable={{is_default_branch}}
            type=sha,format=long

      - id: docker_build
        name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          file: ./python/SphinxRTD.Linux.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}